= mktrs-hello-jps

V2024.1.0


Running with JVM, when starting the application, *Spring* creates the context and uses a lot of memory because it has to scan the packages and 
build every class.
$ mvn spring-boot:run --> Started Application in 1.913 seconds (process running for 2.346)



Running in JVM with AOT it allows the *Spring* creates the context by 
$ mvn clean compile spring-boot:process-aot package
$ java -Dspring.aot.enabled=true -jar <jar-name>
  --> 3.112 seconds (process running for 3.719) mmmm this should be lower that JVM ... ?????
  
Somehow if you want to always generate the AOT by default, add the following node to the *Spring Maven Plugin*

<execution>
	     <id>process-aot</id>
	     <goals>
		 <goal>process-aot</goal>
	     </goals>
	 </execution>
     </executions>
	 
and use a single command instead.

$ mvn clean -Dspring.aot.enabled=true spring-boot:run 

This will run in the JVM but uses the AOT compiled code to decrease start up time

Running using GraalVM (by generating this as native OS native image)

$ mvn clean package -Pnative
$ mvn clean package -Pnative,nativeTest<1>

<1> Check if Mockito can be used in Native Tests as of now. NOTE: The _nativeTest_ requires the Docker Image builder.

To build a Docker image as a GraalVM native image.
$ mvn clean spring-boot:build-image -Pnative
$ docker run --rm -p 8080:8080 [image-name]:[version]

To build a native image locally
$ mvn clean -Pnative native:compile <1>
<1> Requires GraalVM installed in your local machine.

If you are in Windows machine, you must run the latter command inside the installed terminal named "x64 Native Tools Command Prompt".
== References

== Spring Native
* https://www.baeldung.com/spring-6-ahead-of-time-optimizations[Ahead of Time Optimizations in Spring 6^]
* https://www.baeldung.com/spring-native-intro[Native Images with Spring Boot and GraalVM^]
* https://spring.io/blog/2023/09/09/all-together-now-spring-boot-3-2-graalvm-native-images-java-21-and-virtual [All together now: Spring Boot 3.2, GraalVM native images, Java 21, and virtual threads with Project Loom^]
* https://medium.com/ekino-france/native-image-with-spring-boot-70f32788528c[Native Image with Spring Boot^]

== GraalVM
* https://www.graalvm.org/latest/docs/getting-started/windows/[Installation on Windows Platforms^]
* https://www.graalvm.org/downloads/[GraalVM Downloads]
* https://github.com/graalvm[GraalVM on Github^]

